import type {
  Application,
  DebtTrade,
  DocumentKind,
  DocumentStatus,
  IncomeWorksheet,
  Liability,
  Notes,
  Person,
  UploadedDocument,
  WorkflowStatus,
} from "./types";

const emptyNotes = (): Notes => ({
  income: "",
  creditScore: "",
  degree: "",
  fico: "",
  documentation: "",
  payoff: "",
  general: "",
});

const defaultIncome = (overrides: Partial<IncomeWorksheet> = {}): IncomeWorksheet => ({
  selectedFrequency: "biweekly",
  grossPay: 0,
  hours: 40,
  payPeriods: 16,
  variableYtd: 0,
  variablePayPeriods: 0,
  priorYearIncome: 0,
  housingPayment: 0,
  estimatedNewPayment: 0,
  ...overrides,
});

function doc(partial: {
  id: string;
  name: string;
  kind: DocumentKind;
  typeLabel: string;
  description: string;
  fileName: string;
  uploadedAt: string;
  sourceStatus?: string;
  reviewStatus?: DocumentStatus;
}): UploadedDocument {
  return {
    sourceStatus: "",
    reviewStatus: "pending",
    reviewedAt: null,
    note: "",
    ...partial,
  };
}

function liability(partial: Omit<Liability, "confirmed" | "selected" | "payoffType"> & Partial<Liability>): Liability {
  return {
    selected: false,
    payoffType: "full",
    confirmed: false,
    ...partial,
  };
}

function tradesFromLiabilities(items: Liability[]): DebtTrade[] {
  return items.map((item) => ({
    id: item.id,
    tradeType: item.category === "EDUCATIONAL" ? "Student Loan" : item.category,
    accountNumber: item.accountNumber,
    lender: item.lender,
    category: item.category,
    accountType: item.accountType,
    highCredit: item.highCredit,
    balance: item.balance,
    payment: item.payment,
    includeInDti: item.payment > 0,
  }));
}

const madelineLiabilities: Liability[] = [
  liability({
    id: "sm-1",
    lender: "SALLIE MAE",
    accountNumber: "5852504401645782",
    loanIdentifier: "5782",
    category: "EDUCATIONAL",
    accountType: "I",
    highCredit: 8200,
    balance: 6357,
    payment: 1,
    selected: true,
    adjCreditorName: "SALLIE MAE",
    adjAccountNumber: "5299368316",
    adjBalance: 6430.87,
    source: "sallie-mae",
  }),
  liability({
    id: "sm-2",
    lender: "SALLIE MAE",
    accountNumber: "5852504401644411",
    loanIdentifier: "4411",
    category: "EDUCATIONAL",
    accountType: "I",
    highCredit: 9800,
    balance: 9720,
    payment: 0,
    selected: true,
    adjCreditorName: "SALLIE MAE",
    adjAccountNumber: "5299368317",
    adjBalance: 9800,
    source: "sallie-mae",
  }),
  liability({
    id: "sm-3",
    lender: "SALLIE MAE",
    accountNumber: "5852504401643309",
    loanIdentifier: "3309",
    category: "EDUCATIONAL",
    accountType: "I",
    highCredit: 11200,
    balance: 11040,
    payment: 0,
    selected: true,
    adjCreditorName: "SALLIE MAE",
    adjAccountNumber: "5299368318",
    adjBalance: 11200,
    source: "sallie-mae",
  }),
  liability({
    id: "sm-4",
    lender: "SALLIE MAE",
    accountNumber: "5852504401642208",
    loanIdentifier: "2208",
    category: "EDUCATIONAL",
    accountType: "I",
    highCredit: 8500,
    balance: 8310,
    payment: 0,
    selected: true,
    adjCreditorName: "SALLIE MAE",
    adjAccountNumber: "5299368319",
    adjBalance: 8450,
    source: "sallie-mae",
  }),
  liability({
    id: "sm-5",
    lender: "SALLIE MAE",
    accountNumber: "5852504401641107",
    loanIdentifier: "1107",
    category: "EDUCATIONAL",
    accountType: "I",
    highCredit: 15500,
    balance: 15210,
    payment: 0,
    selected: true,
    adjCreditorName: "SALLIE MAE",
    adjAccountNumber: "5299368320",
    adjBalance: 15478.84,
    source: "sallie-mae",
  }),
  liability({
    id: "sm-6",
    lender: "SALLIE MAE",
    accountNumber: "5852504401640096",
    loanIdentifier: "0096",
    category: "EDUCATIONAL",
    accountType: "I",
    highCredit: 16200,
    balance: 15880,
    payment: 0,
    selected: true,
    adjCreditorName: "SALLIE MAE",
    adjAccountNumber: "5299368321",
    adjBalance: 16000,
    source: "sallie-mae",
  }),
  liability({
    id: "mo-1",
    lender: "MISSOURI HIGHER EDUC",
    accountNumber: "1E00120190814240104",
    loanIdentifier: "0104",
    category: "EDUCATIONAL",
    accountType: "I",
    highCredit: 3600,
    balance: 3529,
    payment: 50,
    adjCreditorName: "MISSOURI HIGHER EDUC",
    adjAccountNumber: "1E00120190814240104",
    adjBalance: 3529,
    source: "credit-report",
  }),
  liability({
    id: "mo-2",
    lender: "MISSOURI HIGHER EDUC",
    accountNumber: "1E00120190814240211",
    loanIdentifier: "0211",
    category: "EDUCATIONAL",
    accountType: "I",
    highCredit: 8700,
    balance: 8591,
    payment: 64.43,
    adjCreditorName: "MISSOURI HIGHER EDUC",
    adjAccountNumber: "1E00120190814240211",
    adjBalance: 8591,
    source: "credit-report",
  }),
  liability({
    id: "mo-3",
    lender: "MISSOURI HIGHER EDUC",
    accountNumber: "1E00120190814240328",
    loanIdentifier: "0328",
    category: "EDUCATIONAL",
    accountType: "I",
    highCredit: 4600,
    balance: 4522,
    payment: 50,
    adjCreditorName: "MISSOURI HIGHER EDUC",
    adjAccountNumber: "1E00120190814240328",
    adjBalance: 4522,
    source: "credit-report",
  }),
  liability({
    id: "cc-1",
    lender: "COMENITYCAPITAL/CREDIT_CARD",
    accountNumber: "414709118822",
    loanIdentifier: "8822",
    category: "CREDIT_CARD",
    accountType: "R",
    highCredit: 2500,
    balance: 1840,
    payment: 37,
    adjCreditorName: "COMENITYCAPITAL/CREDIT_CARD",
    adjAccountNumber: "414709118822",
    adjBalance: 1840,
    source: "credit-report",
  }),
  liability({
    id: "ca-1",
    lender: "COLLEGE AVENUE S",
    accountNumber: "9004412281",
    loanIdentifier: "2281",
    category: "EDUCATIONAL",
    accountType: "I",
    highCredit: 12500,
    balance: 11840,
    payment: 112,
    adjCreditorName: "COLLEGE AVENUE S",
    adjAccountNumber: "9004412281",
    adjBalance: 11840,
    source: "credit-report",
  }),
];

const madeline: Application = {
  id: "1411011",
  opportunityName: "Madeline Prusinowski-1411011",
  recordType: "Tavant",
  stage: "UW - PreReview",
  amount: 67359.71,
  requestedTerm: 240,
  requestedRateType: "Fixed",
  applicationDate: "2026-08-20T20:39:00",
  hardCreditDate: "2026-08-16T08:12:00",
  preReviewAt: "2026-08-28T09:24:00",
  priority: 1,
  difficulty: "Medium",
  referrer: "Credible",
  underwriter: "Elizabeth Tascione",
  owner: "Jordan Hale",
  borrower: {
    fullName: "Madeline Prusinowski",
    email: "m.prusinowski@email.com",
    zip: "48009",
    state: "MI",
    filingStatus: "Single",
    birthDate: "1998-04-12",
    creditScore: 718,
    fico: 722,
    statedAnnualIncome: 74000,
    degree: "Bachelor of Science, Nursing",
    school: "University of Missouri",
  },
  cosigner: null,
  employment: [
    {
      employer: "Beaumont Hospital",
      title: "Registered Nurse",
      startDate: "2024-06-03",
      status: "Full-time",
      monthlyIncome: 6166.66,
    },
  ],
  documents: [
    doc({
      id: "d-id",
      name: "Identity Verification",
      kind: "identity",
      typeLabel: "Identification",
      description: "Identity Return",
      fileName: "Identity_Verification_V1.pdf",
      uploadedAt: "2026-08-20T20:39:00",
      sourceStatus: "Submitted",
    }),
    doc({
      id: "d-kyc",
      name: "KYC / CIP",
      kind: "kyc",
      typeLabel: "KYC",
      description: "Customer identification program",
      fileName: "KYC_CIP_1411011.pdf",
      uploadedAt: "2026-08-20T20:40:00",
      sourceStatus: "Submitted",
    }),
    doc({
      id: "d-cse",
      name: "Credit Score Exception Notice",
      kind: "credit-score-exception",
      typeLabel: "Credit Score Exception Notice",
      description: "Credit Score Exception Notice",
      fileName: "Credit_Score_Exception_Notice.pdf",
      uploadedAt: "2026-08-20T20:39:00",
    }),
    doc({
      id: "d-cr",
      name: "Credit Report",
      kind: "credit-report",
      typeLabel: "Credit Report",
      description: "Hard pull",
      fileName: "HardPullFile_563852.pdf",
      uploadedAt: "2026-08-20T20:39:00",
      sourceStatus: "Submitted",
    }),
    doc({
      id: "d-mla",
      name: "MLA Verification",
      kind: "mla",
      typeLabel: "MLA Verification",
      description: "Military Leave Act Return",
      fileName: "Equifax_MLA_Verification.pdf",
      uploadedAt: "2026-08-20T20:39:00",
    }),
    doc({
      id: "d-deg",
      name: "Degree / Transcript",
      kind: "degree",
      typeLabel: "Education",
      description: "Bachelor of Science, Nursing — University of Missouri",
      fileName: "Degree_Verification_UM.pdf",
      uploadedAt: "2026-08-21T09:12:00",
      sourceStatus: "Submitted",
    }),
    doc({
      id: "d-ps1",
      name: "Pay Stub — Current",
      kind: "pay-stub",
      typeLabel: "Income",
      description: "Biweekly pay stub ending 08/15/2026",
      fileName: "Paystub_08152026.pdf",
      uploadedAt: "2026-08-21T09:14:00",
      sourceStatus: "Submitted",
    }),
    doc({
      id: "d-ps2",
      name: "Pay Stub — Prior",
      kind: "pay-stub",
      typeLabel: "Income",
      description: "Biweekly pay stub ending 08/01/2026",
      fileName: "Paystub_08012026.pdf",
      uploadedAt: "2026-08-21T09:14:00",
      sourceStatus: "Submitted",
    }),
  ],
  liabilities: madelineLiabilities,
  income: defaultIncome({
    selectedFrequency: "biweekly",
    grossPay: 2846.15,
    payPeriods: 16,
    housingPayment: 1450,
    estimatedNewPayment: 542.18,
    priorYearIncome: 71000,
  }),
  debtTrades: tradesFromLiabilities(madelineLiabilities),
  notes: emptyNotes(),
  status: "pre-review",
  decision: "",
  seniorNotes: "",
  seniorDecision: "",
  submittedAt: null,
  returnedAt: null,
  approvedAt: null,
  primarySnapshot: null,
  lastSavedAt: null,
};

const sampleCosigner: Person = {
  fullName: "Alex Rivera",
  email: "alex.rivera@email.com",
  zip: "30308",
  state: "GA",
  filingStatus: "Single",
  birthDate: "1972-09-04",
  creditScore: 741,
  fico: 744,
  statedAnnualIncome: 98000,
  degree: "Bachelor of Arts",
  school: "University of Georgia",
};

function lightApplication(input: {
  id: string;
  name: string;
  recordType: Application["recordType"];
  amount: number;
  priority: number;
  difficulty: Application["difficulty"];
  referrer: string;
  underwriter: string;
  owner: string;
  applicationDate: string;
  hardCreditDate: string;
  preReviewAt: string;
  status?: WorkflowStatus;
  email: string;
  state: string;
  hasCosigner?: boolean;
}): Application {
  const cloneLiabilities = madelineLiabilities.map((item, index) => ({
    ...item,
    id: `${input.id}-${item.id}`,
    selected: index < 3,
    confirmed: false,
    adjBalance: Math.round(item.adjBalance * (input.amount / 67359.71) * 100) / 100,
  }));

  return {
    ...madeline,
    id: input.id,
    opportunityName: `${input.name}-${input.id}`,
    recordType: input.recordType,
    amount: input.amount,
    applicationDate: input.applicationDate,
    hardCreditDate: input.hardCreditDate,
    preReviewAt: input.preReviewAt,
    priority: input.priority,
    difficulty: input.difficulty,
    referrer: input.referrer,
    underwriter: input.underwriter,
    owner: input.owner,
    status: input.status ?? "pre-review",
    cosigner: input.hasCosigner ? sampleCosigner : null,
    borrower: {
      ...madeline.borrower,
      fullName: input.name,
      email: input.email,
      state: input.state,
    },
    liabilities: cloneLiabilities,
    debtTrades: tradesFromLiabilities(cloneLiabilities),
    documents: madeline.documents.map((item) => ({
      ...item,
      id: `${input.id}-${item.id}`,
      reviewStatus: "pending" as DocumentStatus,
      reviewedAt: null,
      note: "",
    })),
    notes: emptyNotes(),
    decision: "",
    seniorNotes: "",
    seniorDecision: "",
    submittedAt: null,
    returnedAt: null,
    approvedAt: null,
    primarySnapshot: null,
    lastSavedAt: null,
  };
}

export const seedApplications: Application[] = [
  madeline,
  lightApplication({
    id: "1409678",
    name: "Madison Ventura",
    recordType: "InSchool",
    amount: 28400,
    priority: 2,
    difficulty: "Medium",
    referrer: "Splash",
    underwriter: "Gage Lawson",
    owner: "Ava Chen",
    applicationDate: "2026-08-27T11:20:00",
    hardCreditDate: "2026-08-16T10:02:00",
    preReviewAt: "2026-08-28T09:10:00",
    email: "madison.ventura@email.com",
    state: "TX",
    hasCosigner: true,
  }),
  lightApplication({
    id: "1410724",
    name: "Robert Wendland",
    recordType: "InSchool",
    amount: 41200,
    priority: 3,
    difficulty: "Hard",
    referrer: "Paid Search",
    underwriter: "Joshua Mitchell",
    owner: "Chris Patel",
    applicationDate: "2026-08-26T16:40:00",
    hardCreditDate: "2026-08-18T09:00:00",
    preReviewAt: "2026-08-28T08:44:00",
    email: "r.wendland@email.com",
    state: "OH",
    hasCosigner: true,
  }),
  lightApplication({
    id: "1408122",
    name: "Priya Shah",
    recordType: "InSchool",
    amount: 164109.45,
    priority: 1,
    difficulty: "Hard",
    referrer: "NerdWallet",
    underwriter: "Michael Gabaldon",
    owner: "Sam Ortiz",
    applicationDate: "2026-08-25T14:12:00",
    hardCreditDate: "2026-08-15T13:22:00",
    preReviewAt: "2026-08-28T08:12:00",
    email: "priya.shah@email.com",
    state: "CA",
    hasCosigner: true,
  }),
  lightApplication({
    id: "1407441",
    name: "Noah Ellis",
    recordType: "InSchool",
    amount: 4000,
    priority: 6,
    difficulty: "Medium",
    referrer: "Credible",
    underwriter: "Colene Helveston",
    owner: "Jordan Hale",
    applicationDate: "2026-08-27T09:05:00",
    hardCreditDate: "2026-08-20T11:48:00",
    preReviewAt: "2026-08-28T07:55:00",
    email: "noah.ellis@email.com",
    state: "FL",
    hasCosigner: true,
  }),
  lightApplication({
    id: "1411988",
    name: "Grace Okonkwo",
    recordType: "Tavant",
    amount: 55210,
    priority: 2,
    difficulty: "Medium",
    referrer: "Splash",
    underwriter: "Nolan Carpenter",
    owner: "Ava Chen",
    applicationDate: "2026-08-24T18:30:00",
    hardCreditDate: "2026-08-19T08:16:00",
    preReviewAt: "2026-08-28T07:40:00",
    email: "grace.okonkwo@email.com",
    state: "GA",
  }),
  lightApplication({
    id: "1410033",
    name: "Luis Herrera",
    recordType: "Tavant",
    amount: 88950,
    priority: 4,
    difficulty: "Hard",
    referrer: "Paid Search",
    underwriter: "Lexi Wright",
    owner: "Chris Patel",
    applicationDate: "2026-08-23T12:08:00",
    hardCreditDate: "2026-08-17T15:41:00",
    preReviewAt: "2026-08-28T07:22:00",
    email: "luis.herrera@email.com",
    state: "AZ",
  }),
  lightApplication({
    id: "1406550",
    name: "Hannah Brooks",
    recordType: "Tavant",
    amount: 32600,
    priority: 5,
    difficulty: "Medium",
    referrer: "NerdWallet",
    underwriter: "Elizabeth Tascione",
    owner: "Sam Ortiz",
    applicationDate: "2026-08-22T10:17:00",
    hardCreditDate: "2026-08-14T09:55:00",
    preReviewAt: "2026-08-27T16:05:00",
    email: "hannah.brooks@email.com",
    state: "CO",
  }),
];
