import type {
  Application,
  DebtTrade,
  DocumentKind,
  DocumentStatus,
  IncomeWorksheet,
  Liability,
  Notes,
  Person,
  UploadedDocument,
  WorkflowStatus,
} from "./types";
import { estimatedPayment, seedCalculator } from "./calculations/income";
import { defaultLenderAddresses } from "./payoffs";

const PRIMARY_AMOUNT = 62494.9;

const emptyNotes = (): Notes => ({
  income: "",
  creditScore: "",
  degree: "",
  fico: "",
  documentation: "",
  payoff: "",
  general: "",
});

const defaultIncome = (overrides: Partial<IncomeWorksheet> = {}): IncomeWorksheet => {
  const income = {
    selectedFrequency: "biweekly" as const,
    grossPay: 0,
    hours: 40,
    payPeriods: 16,
    variableYtd: 0,
    variablePayPeriods: 0,
    priorYearIncome: 0,
    housingPayment: 0,
    estimatedNewPayment: 0,
    ...overrides,
  };
  return {
    ...income,
    calculator: overrides.calculator ?? seedCalculator(income),
  };
};

function round2(value: number): number {
  return Math.round(value * 100) / 100;
}

function doc(partial: {
  id: string;
  name: string;
  kind: DocumentKind;
  typeLabel: string;
  description: string;
  fileName: string;
  uploadedAt: string;
  sourceStatus?: string;
  reviewStatus?: DocumentStatus;
  internal?: boolean;
}): UploadedDocument {
  return {
    sourceStatus: "",
    reviewStatus: "pending",
    reviewedAt: null,
    note: "",
    internal: false,
    ...partial,
  };
}

function liability(
  partial: Omit<
    Liability,
    "confirmed" | "selected" | "payoffType" | "adjLoanIdentifier" | "lenderAddresses" | "selectedAddress"
  > &
    Partial<Liability>,
): Liability {
  const addresses = partial.lenderAddresses ?? defaultLenderAddresses(partial.lender);
  return {
    selected: false,
    payoffType: "full",
    confirmed: false,
    adjLoanIdentifier: "",
    ...partial,
    lenderAddresses: addresses,
    selectedAddress: partial.selectedAddress ?? addresses[0] ?? "",
  };
}

function trade(
  partial: Omit<DebtTrade, "sysPayment" | "adjPayment" | "originalBalance"> & Partial<DebtTrade>,
): DebtTrade {
  return {
    ...partial,
    sysPayment: partial.sysPayment ?? partial.payment,
    adjPayment: partial.adjPayment ?? partial.payment,
    originalBalance: partial.originalBalance ?? partial.highCredit,
  };
}

function creditReportTrades(prefix = ""): DebtTrade[] {
  const id = (key: string) => (prefix ? `${prefix}-${key}` : key);
  return [
    trade({
      id: id("cr-auto-1"),
      tradeType: "Installment",
      accountNumber: "4482017731",
      lender: "EQUIFAX TEST DATA",
      category: "AUTOMOBILE",
      accountType: "I",
      highCredit: 40630,
      balance: 27555,
      payment: 559,
      reportedAt: "10/2025",
      ecoa: "J",
      includeInDti: true,
    }),
    trade({
      id: id("cr-card-1"),
      tradeType: "Revolving",
      accountNumber: "4482018842",
      lender: "EQUIFAX TEST DATA",
      category: "CREDIT_CARD",
      accountType: "R",
      highCredit: 1226,
      balance: 0,
      payment: 0,
      reportedAt: "10/2025",
      ecoa: "A",
      includeInDti: false,
    }),
    trade({
      id: id("cr-heloc-1"),
      tradeType: "Line of credit",
      accountNumber: "4482019953",
      lender: "EQUIFAX TEST DATA",
      category: "HOME_EQUITY_LINE_OF_CREDIT",
      accountType: "C",
      highCredit: 10060,
      balance: 0,
      payment: 0,
      reportedAt: "10/2025",
      ecoa: "I",
      includeInDti: false,
    }),
    trade({
      id: id("cr-card-2"),
      tradeType: "Revolving",
      accountNumber: "4482020064",
      lender: "EQUIFAX TEST DATA",
      category: "CREDIT_CARD",
      accountType: "R",
      highCredit: 3561,
      balance: 0,
      payment: 0,
      reportedAt: "10/2025",
      ecoa: "I",
      includeInDti: false,
    }),
    trade({
      id: id("cr-card-3"),
      tradeType: "Revolving",
      accountNumber: "4482021175",
      lender: "EQUIFAX TEST DATA",
      category: "CREDIT_CARD",
      accountType: "R",
      highCredit: 0,
      balance: 0,
      payment: 0,
      reportedAt: "10/2025",
      ecoa: "I",
      includeInDti: false,
    }),
    trade({
      id: id("cr-card-4"),
      tradeType: "Revolving",
      accountNumber: "4482022286",
      lender: "EQUIFAX TEST DATA",
      category: "CREDIT_CARD",
      accountType: "R",
      highCredit: 3528,
      balance: 0,
      payment: 0,
      reportedAt: "10/2025",
      ecoa: "I",
      includeInDti: false,
    }),
    trade({
      id: id("cr-mtg-1"),
      tradeType: "Mortgage",
      accountNumber: "4482023397",
      lender: "EQUIFAX TEST DATA",
      category: "FHA_REAL_ESTATE_MORTGAGE",
      accountType: "M",
      highCredit: 79256,
      balance: 67054,
      payment: 586,
      reportedAt: "10/2025",
      ecoa: "J",
      includeInDti: true,
    }),
    trade({
      id: id("cr-card-5"),
      tradeType: "Revolving",
      accountNumber: "4482024408",
      lender: "EQUIFAX TEST DATA",
      category: "FlexibleSpendingCreditCard",
      accountType: "R",
      highCredit: 8611,
      balance: 3916,
      payment: 78,
      reportedAt: "10/2025",
      ecoa: "I",
      includeInDti: true,
    }),
    trade({
      id: id("cr-auto-2"),
      tradeType: "Installment",
      accountNumber: "4482025519",
      lender: "EQUIFAX TEST DATA",
      category: "AUTOMOBILE",
      accountType: "I",
      highCredit: 21158,
      balance: 0,
      payment: 0,
      reportedAt: "06/2021",
      ecoa: "I",
      includeInDti: false,
    }),
  ];
}

const primaryLiabilities: Liability[] = [
  liability({
    id: "sm-1",
    lender: "SALLIE MAE",
    accountNumber: "6001842291766408",
    loanIdentifier: "6408",
    category: "EDUCATIONAL",
    accountType: "I",
    highCredit: 7600,
    balance: 6120,
    payment: 1,
    selected: true,
    adjCreditorName: "SALLIE MAE",
    adjAccountNumber: "6001842200842216",
    adjBalance: 6188.4,
    source: "sallie-mae",
  }),
  liability({
    id: "sm-2",
    lender: "SALLIE MAE",
    accountNumber: "6001842291764419",
    loanIdentifier: "4419",
    category: "EDUCATIONAL",
    accountType: "I",
    highCredit: 9100,
    balance: 8940,
    payment: 0,
    selected: true,
    adjCreditorName: "SALLIE MAE",
    adjAccountNumber: "6001842200843327",
    adjBalance: 9100,
    source: "sallie-mae",
  }),
  liability({
    id: "sm-3",
    lender: "SALLIE MAE",
    accountNumber: "6001842291763301",
    loanIdentifier: "3301",
    category: "EDUCATIONAL",
    accountType: "I",
    highCredit: 10400,
    balance: 10180,
    payment: 0,
    selected: true,
    adjCreditorName: "SALLIE MAE",
    adjAccountNumber: "6001842200844438",
    adjBalance: 10400,
    source: "sallie-mae",
  }),
  liability({
    id: "sm-4",
    lender: "SALLIE MAE",
    accountNumber: "6001842291762206",
    loanIdentifier: "2206",
    category: "EDUCATIONAL",
    accountType: "I",
    highCredit: 7900,
    balance: 7710,
    payment: 0,
    selected: true,
    adjCreditorName: "SALLIE MAE",
    adjAccountNumber: "6001842200845549",
    adjBalance: 7840,
    source: "sallie-mae",
  }),
  liability({
    id: "sm-5",
    lender: "SALLIE MAE",
    accountNumber: "6001842291761104",
    loanIdentifier: "1104",
    category: "EDUCATIONAL",
    accountType: "I",
    highCredit: 14200,
    balance: 13940,
    payment: 0,
    selected: true,
    adjCreditorName: "SALLIE MAE",
    adjAccountNumber: "6001842200846650",
    adjBalance: 14166.5,
    source: "sallie-mae",
  }),
  liability({
    id: "sm-6",
    lender: "SALLIE MAE",
    accountNumber: "6001842291760093",
    loanIdentifier: "0093",
    category: "EDUCATIONAL",
    accountType: "I",
    highCredit: 15000,
    balance: 14680,
    payment: 0,
    selected: true,
    adjCreditorName: "SALLIE MAE",
    adjAccountNumber: "6001842200847761",
    adjBalance: 14800,
    source: "sallie-mae",
  }),
  liability({
    id: "sa-1",
    lender: "LAKESHORE STUDENT AID",
    accountNumber: "9E88220190815550117",
    loanIdentifier: "0117",
    category: "EDUCATIONAL",
    accountType: "I",
    highCredit: 3400,
    balance: 3310,
    payment: 48,
    adjCreditorName: "LAKESHORE STUDENT AID",
    adjAccountNumber: "9E88220190815550117",
    adjBalance: 3310,
    source: "credit-report",
  }),
  liability({
    id: "sa-2",
    lender: "LAKESHORE STUDENT AID",
    accountNumber: "9E88220190815550228",
    loanIdentifier: "0228",
    category: "EDUCATIONAL",
    accountType: "I",
    highCredit: 8100,
    balance: 7980,
    payment: 61.2,
    adjCreditorName: "LAKESHORE STUDENT AID",
    adjAccountNumber: "9E88220190815550228",
    adjBalance: 7980,
    source: "credit-report",
  }),
  liability({
    id: "sa-3",
    lender: "LAKESHORE STUDENT AID",
    accountNumber: "9E88220190815550339",
    loanIdentifier: "0339",
    category: "EDUCATIONAL",
    accountType: "I",
    highCredit: 4300,
    balance: 4195,
    payment: 48,
    adjCreditorName: "LAKESHORE STUDENT AID",
    adjAccountNumber: "9E88220190815550339",
    adjBalance: 4195,
    source: "credit-report",
  }),
  liability({
    id: "cc-1",
    lender: "RIVERSTONE CARD",
    accountNumber: "600188447731",
    loanIdentifier: "7731",
    category: "CREDIT_CARD",
    accountType: "R",
    highCredit: 2800,
    balance: 1960,
    payment: 39,
    adjCreditorName: "RIVERSTONE CARD",
    adjAccountNumber: "600188447731",
    adjBalance: 1960,
    source: "credit-report",
  }),
  liability({
    id: "hl-1",
    lender: "HARBOR STUDENT LENDING",
    accountNumber: "8116623947",
    loanIdentifier: "3947",
    category: "EDUCATIONAL",
    accountType: "I",
    highCredit: 11800,
    balance: 10950,
    payment: 108,
    adjCreditorName: "HARBOR STUDENT LENDING",
    adjAccountNumber: "8116623947",
    adjBalance: 10950,
    source: "credit-report",
  }),
];

function samplePayoffs(prefix = ""): Liability[] {
  const id = (key: string) => (prefix ? `${prefix}-${key}` : key);
  return [
    liability({
      id: id("po-1"),
      lender: "SALLIE MAE",
      accountNumber: "1E00181230912312312093",
      loanIdentifier: "",
      category: "EDUCATIONAL",
      accountType: "I",
      highCredit: 13559,
      balance: 13559,
      payment: 160,
      adjCreditorName: "",
      adjAccountNumber: "",
      adjBalance: 0,
      source: "sallie-mae",
    }),
    liability({
      id: id("po-2"),
      lender: "SALLIE MAE",
      accountNumber: "1E00181230912312322104",
      loanIdentifier: "",
      category: "EDUCATIONAL",
      accountType: "I",
      highCredit: 9840,
      balance: 9840,
      payment: 142,
      adjCreditorName: "",
      adjAccountNumber: "",
      adjBalance: 0,
      source: "sallie-mae",
    }),
    liability({
      id: id("po-3"),
      lender: "LAKESHORE STUDENT AID",
      accountNumber: "9E88220190815550117",
      loanIdentifier: "",
      category: "EDUCATIONAL",
      accountType: "I",
      highCredit: 11275,
      balance: 11275,
      payment: 155,
      adjCreditorName: "",
      adjAccountNumber: "",
      adjBalance: 0,
      source: "credit-report",
    }),
  ];
}

const elena: Application = {
  id: "2084417",
  opportunityName: "Elena Voss-2084417",
  recordType: "Tavant",
  stage: "UW - PreReview",
  amount: PRIMARY_AMOUNT,
  requestedTerm: 60,
  requestedRateType: "Fixed",
  applicationDate: "2026-08-20T20:39:00",
  hardCreditDate: "2026-08-16T08:12:00",
  preReviewAt: "2026-08-28T09:24:00",
  priority: 1,
  difficulty: "Medium",
  referrer: "Credible",
  underwriter: "Dana Whitfield",
  owner: "Nolan Keene",
  borrower: {
    fullName: "Elena Voss",
    email: "elena.voss@example.com",
    zip: "55113",
    state: "MN",
    street: "418 Snelling Ave N",
    city: "Roseville",
    phone: "(651) 555-0144",
    ssnLast4: "4417",
    citizenship: "U.S Citizen",
    graduationYear: "2018",
    relationship: "",
    livingArrangement: "Renting",
    filingStatus: "Single",
    birthDate: "1996-09-21",
    creditScore: 731,
    fico: 734,
    statedAnnualIncome: 68900,
    degree: "Bachelor of Science, Nursing",
    school: "Midwest State University",
  },
  cosigner: null,
  employment: [
    {
      employer: "Riverside Medical Center",
      title: "Registered Nurse",
      startDate: "2024-06-03",
      status: "Full-time",
      monthlyIncome: 5741.67,
    },
  ],
  documents: [
    doc({
      id: "d-id",
      name: "Internal Identity Verification",
      kind: "identity",
      typeLabel: "Identification",
      description: "Identity Return",
      fileName: "Identity_Verification_[V1].pdf",
      uploadedAt: "2025-12-15T01:38:00-05:00",
      internal: true,
    }),
    doc({
      id: "d-kyc",
      name: "KYC / CIP",
      kind: "kyc",
      typeLabel: "KYC",
      description: "Customer identification program",
      fileName: "KYC_CIP_2084417.pdf",
      uploadedAt: "2025-12-15T01:38:00-05:00",
      sourceStatus: "Submitted",
      internal: true,
    }),
    doc({
      id: "d-cse",
      name: "Credit Score Exception Notice",
      kind: "credit-score-exception",
      typeLabel: "Credit Score Exception Notice",
      description: "Credit Score Exception Notice",
      fileName: "Credit Score Exception Notice.pdf",
      uploadedAt: "2025-12-15T01:38:00-05:00",
    }),
    doc({
      id: "d-cr",
      name: "Credit Report",
      kind: "credit-report",
      typeLabel: "Credit Report",
      description: "",
      fileName: "HardPullFile_5857.pdf",
      uploadedAt: "2025-12-15T01:38:00-05:00",
      sourceStatus: "Submitted",
      internal: true,
    }),
    doc({
      id: "d-mla",
      name: "MLA Verification",
      kind: "mla",
      typeLabel: "MLA Verification",
      description: "Military Leave Act Return",
      fileName: "Equifax_MLA_Verification.pdf",
      uploadedAt: "2025-12-15T01:38:00-05:00",
      internal: true,
    }),
    doc({
      id: "d-disc",
      name: "Application Disclosure Variable",
      kind: "application-disclosure",
      typeLabel: "Application Disclosure Variable",
      description: "Application Disclosure Variable",
      fileName: "Application_Disclosure.pdf",
      uploadedAt: "2025-12-15T01:38:00-05:00",
    }),
    doc({
      id: "d-deg",
      name: "Degree / Transcript",
      kind: "degree",
      typeLabel: "Education",
      description: "Bachelor of Science, Nursing — Midwest State University",
      fileName: "Degree_Verification_MSU.pdf",
      uploadedAt: "2025-12-15T01:38:00-05:00",
      sourceStatus: "Submitted",
      internal: true,
    }),
    doc({
      id: "d-ps1",
      name: "Pay Stub — Current",
      kind: "pay-stub",
      typeLabel: "Income",
      description: "Biweekly pay stub ending 08/15/2026",
      fileName: "Paystub_08152026.pdf",
      uploadedAt: "2025-12-15T01:38:00-05:00",
      sourceStatus: "Submitted",
    }),
    doc({
      id: "d-ps2",
      name: "Pay Stub — Prior",
      kind: "pay-stub",
      typeLabel: "Income",
      description: "Biweekly pay stub ending 08/01/2026",
      fileName: "Paystub_08012026.pdf",
      uploadedAt: "2025-12-15T01:38:00-05:00",
      sourceStatus: "Submitted",
    }),
  ],
  liabilities: primaryLiabilities,
  payoffs: samplePayoffs(),
  income: defaultIncome({
    selectedFrequency: "biweekly",
    grossPay: 2650,
    payPeriods: 16,
    housingPayment: 1380,
    estimatedNewPayment: round2(estimatedPayment(PRIMARY_AMOUNT, 60, 0.0639)),
    priorYearIncome: 66200,
  }),
  debtTrades: creditReportTrades(),
  notes: emptyNotes(),
  status: "pre-review",
  decision: "",
  seniorNotes: "",
  seniorDecision: "",
  submittedAt: null,
  returnedAt: null,
  approvedAt: null,
  primarySnapshot: null,
  lastSavedAt: null,
  workbookFileName: null,
  workbookUploadedAt: null,
  workbookCopy: null,
  opportunity: {},
  underwriting: {
    borrowerStatus: "UW - PreReview",
    supervisorApproval: false,
    mlaEligible: "no",
    primaryHousingTradeId: "",
  },
};

const sampleCosigner: Person = {
  fullName: "Morgan Phelps",
  email: "morgan.phelps@example.com",
  zip: "30318",
  state: "GA",
  street: "88 Piedmont Ave NE",
  city: "Atlanta",
  phone: "(404) 555-0198",
  ssnLast4: "0318",
  citizenship: "U.S Citizen",
  graduationYear: "1996",
  relationship: "Parent",
  livingArrangement: "Owning",
  filingStatus: "Single",
  birthDate: "1974-11-18",
  creditScore: 752,
  fico: 755,
  statedAnnualIncome: 91200,
  degree: "Bachelor of Arts",
  school: "Northridge College",
};

function cloneLiabilitiesFor(id: string, amount: number): Liability[] {
  const scale = amount / PRIMARY_AMOUNT;
  const items = primaryLiabilities.map((item) => ({
    ...item,
    id: `${id}-${item.id}`,
    highCredit: round2(item.highCredit * scale),
    balance: round2(item.balance * scale),
    adjBalance: round2(item.adjBalance * scale),
    payment: round2(item.payment * scale),
    selected: item.source === "sallie-mae",
    confirmed: false,
  }));
  const selected = items.filter((item) => item.selected);
  const sum = selected.reduce((total, item) => total + item.adjBalance, 0);
  const last = selected[selected.length - 1];
  if (last) last.adjBalance = round2(last.adjBalance + (amount - sum));
  return items;
}

function lightApplication(input: {
  id: string;
  name: string;
  recordType: Application["recordType"];
  amount: number;
  priority: number;
  difficulty: Application["difficulty"];
  referrer: string;
  underwriter: string;
  owner: string;
  applicationDate: string;
  hardCreditDate: string;
  preReviewAt: string;
  status?: WorkflowStatus;
  email: string;
  state: string;
  hasCosigner?: boolean;
}): Application {
  const liabilities = cloneLiabilitiesFor(input.id, input.amount);

  return {
    ...elena,
    id: input.id,
    opportunityName: `${input.name}-${input.id}`,
    recordType: input.recordType,
    amount: input.amount,
    applicationDate: input.applicationDate,
    hardCreditDate: input.hardCreditDate,
    preReviewAt: input.preReviewAt,
    priority: input.priority,
    difficulty: input.difficulty,
    referrer: input.referrer,
    underwriter: input.underwriter,
    owner: input.owner,
    status: input.status ?? "pre-review",
    cosigner: input.hasCosigner ? sampleCosigner : null,
    borrower: {
      ...elena.borrower,
      fullName: input.name,
      email: input.email,
      state: input.state,
    },
    income: {
      ...elena.income,
      estimatedNewPayment: round2(estimatedPayment(input.amount, 60, 0.0639)),
    },
    liabilities,
    payoffs: samplePayoffs(input.id),
    debtTrades: creditReportTrades(input.id),
    documents: elena.documents.map((item) => ({
      ...item,
      id: `${input.id}-${item.id}`,
      fileName: item.fileName.replace(elena.id, input.id),
      reviewStatus: "pending" as DocumentStatus,
      reviewedAt: null,
      note: "",
    })),
    notes: emptyNotes(),
    decision: "",
    seniorNotes: "",
    seniorDecision: "",
    submittedAt: null,
    returnedAt: null,
    approvedAt: null,
    primarySnapshot: null,
    lastSavedAt: null,
    underwriting: {
      borrowerStatus: input.hasCosigner ? "Awaiting CoSigner Completion" : "UW - PreReview",
      supervisorApproval: false,
      mlaEligible: "no",
      primaryHousingTradeId: "",
    },
  };
}

export const seedApplications: Application[] = [
  elena,
  lightApplication({
    id: "2078834",
    name: "Mara Ellison",
    recordType: "InSchool",
    amount: 31800,
    priority: 2,
    difficulty: "Medium",
    referrer: "Splash",
    underwriter: "Miles Crowe",
    owner: "Ivy Tran",
    applicationDate: "2026-08-27T11:20:00",
    hardCreditDate: "2026-08-16T10:02:00",
    preReviewAt: "2026-08-28T09:10:00",
    email: "mara.ellison@example.com",
    state: "TX",
    hasCosigner: true,
  }),
  lightApplication({
    id: "2081902",
    name: "Theo Lang",
    recordType: "InSchool",
    amount: 44750,
    priority: 3,
    difficulty: "Hard",
    referrer: "Paid Search",
    underwriter: "Harper Quinn",
    owner: "Bennett Cole",
    applicationDate: "2026-08-26T16:40:00",
    hardCreditDate: "2026-08-18T09:00:00",
    preReviewAt: "2026-08-28T08:44:00",
    email: "theo.lang@example.com",
    state: "OH",
    hasCosigner: true,
  }),
  lightApplication({
    id: "2076510",
    name: "Anika Bose",
    recordType: "InSchool",
    amount: 151200,
    priority: 1,
    difficulty: "Hard",
    referrer: "NerdWallet",
    underwriter: "Ravi Mehra",
    owner: "Reese Alvarez",
    applicationDate: "2026-08-25T14:12:00",
    hardCreditDate: "2026-08-15T13:22:00",
    preReviewAt: "2026-08-28T08:12:00",
    email: "anika.bose@example.com",
    state: "CA",
    hasCosigner: true,
  }),
  lightApplication({
    id: "2075208",
    name: "Felix Grant",
    recordType: "InSchool",
    amount: 5200,
    priority: 6,
    difficulty: "Medium",
    referrer: "Credible",
    underwriter: "June Calder",
    owner: "Nolan Keene",
    applicationDate: "2026-08-27T09:05:00",
    hardCreditDate: "2026-08-20T11:48:00",
    preReviewAt: "2026-08-28T07:55:00",
    email: "felix.grant@example.com",
    state: "FL",
    hasCosigner: true,
  }),
  lightApplication({
    id: "2087743",
    name: "Nadia Okoye",
    recordType: "Tavant",
    amount: 49800,
    priority: 2,
    difficulty: "Medium",
    referrer: "Splash",
    underwriter: "Owen Briggs",
    owner: "Ivy Tran",
    applicationDate: "2026-08-24T18:30:00",
    hardCreditDate: "2026-08-19T08:16:00",
    preReviewAt: "2026-08-28T07:40:00",
    email: "nadia.okoye@example.com",
    state: "GA",
  }),
  lightApplication({
    id: "2080199",
    name: "Mateo Ruiz",
    recordType: "Tavant",
    amount: 81200,
    priority: 4,
    difficulty: "Hard",
    referrer: "Paid Search",
    underwriter: "Sasha Lind",
    owner: "Bennett Cole",
    applicationDate: "2026-08-23T12:08:00",
    hardCreditDate: "2026-08-17T15:41:00",
    preReviewAt: "2026-08-28T07:22:00",
    email: "mateo.ruiz@example.com",
    state: "AZ",
  }),
  lightApplication({
    id: "2073381",
    name: "Claire Brennan",
    recordType: "Tavant",
    amount: 36150,
    priority: 5,
    difficulty: "Medium",
    referrer: "NerdWallet",
    underwriter: "Dana Whitfield",
    owner: "Reese Alvarez",
    applicationDate: "2026-08-22T10:17:00",
    hardCreditDate: "2026-08-14T09:55:00",
    preReviewAt: "2026-08-27T16:05:00",
    email: "claire.brennan@example.com",
    state: "CO",
  }),
];
